name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: cd auth && docker build -t requiemleaf/auth .
        
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Push Docker Image
        run: docker push requiemleaf/auth

      
