name: deploy_payments

on:
  push:
    branches:
      - main
    paths:
      - 'payments/**'
  workflow_dispatch: # Corrected key for manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEPLOYMENT
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd payments && docker build -t requiemleaf/payments .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push requiemleaf/payments

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save ticket-resale

      - run: kubectl rollout restart deployment payments-depl
