name: tests-payments
on:
  pull_request:
   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Payments tests
      run: cd payments && npm install && npm run test:ci
